<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<graph directed="1"  xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://www.cs.rpi.edu/XGMML">
 <att name="selected" value="1" type="boolean" />
 <att name="name" value="lol" type="string"/>
 <att name="shared name" value="lol" type="string"/>
  <node id="0" label="0">
  </node>
  <node id="1" label="1">
  </node>
  <node id="2" label="2">
  </node>
  <node id="3" label="3">
  </node>
  <node id="4" label="4">
  </node>
  <node id="5" label="5">
  </node>
  <node id="6" label="6">
  </node>
  <node id="7" label="7">
  </node>
  <node id="8" label="8">
  </node>
  <edge source="0" target="8">
  </edge>
  <edge source="1" target="8">
  </edge>
  <edge source="2" target="8">
  </edge>
  <edge source="3" target="8">
  </edge>
  <edge source="4" target="8">
  </edge>
  <edge source="5" target="8">
  </edge>
  <edge source="6" target="8">
  </edge>
  <edge source="7" target="8">
  </edge>
</graph>
